# Generated by Django 4.2.25 on 2026-01-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('elapsed_time', models.FloatField()),
                ('type', models.TextField()),
                ('average_speed', models.FloatField()),
                ('max_speed', models.FloatField()),
                ('average_cadence', models.FloatField()),
                ('average_heartrate', models.FloatField()),
                ('max_heartrate', models.FloatField()),
                ('suffer_score', models.FloatField()),
                ('calories', models.FloatField()),
                ('gear_name', models.TextField()),
                ('description', models.TextField()),
                ('distance', models.FloatField()),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'activities',
            },
        ),
    ]
